### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by special1004** [ZBX05/Intelligent_Health_Prescription_System#1]
hi，我们是一家在线教育网站，偶然关注到您的这个项目，感觉非常适合大学生学习，想问问您是否有兴趣结合此项目制作课程，课程上线后相信会为您带来不错的收益，若有兴趣尝试，欢迎联系我们的官方合作微信：shiyanloukecheng～

**Comment by ZBX05** [comment]
感谢您的关注，我对制作课程不太感兴趣。如果您在后续的工作中需要使用本项目的代码，您可在任意的合法的场景下使用，只需注明出处即可。
